#pragma once

#include "driver/i2c_types.h"
#include "driver/spi_master.h"
#include "driver/uart.h"

/* WiFi station credentials for the embedded dashboard. */
#define WIFI_STA_SSID "Verizon_W9TKP7"
#define WIFI_STA_PASSWORD "rung-paw3-cob"
#define WIFI_CONNECT_TIMEOUT_MS 15000

#define I2C_MASTER_PORT I2C_NUM_0
#define I2C_MASTER_SDA_IO 8
#define I2C_MASTER_SCL_IO 9
#define I2C_MASTER_FREQ_HZ 100000
#define I2C_TRANSMIT_TIMEOUT_MS 100

#define SPI_MASTER_HOST SPI2_HOST
/* BNO08x SPI pin mapping with the board labels:
 * SCL = SCK, SDA = SO/MISO, AD0 = SI/MOSI.
 */
#define SPI_MASTER_MOSI_IO 6
#define SPI_MASTER_MISO_IO 7
#define SPI_MASTER_SCLK_IO 5
#define SPI_MASTER_MAX_TRANSFER_SIZE 1024
#define SPI_MASTER_DEVICE_FREQ_HZ 1000000
#define SPI_MASTER_DEVICE_MODE 3
#define SPI_MASTER_DEVICE_QUEUE_SIZE 1

#define BNO08X_SPI_MOSI_IO SPI_MASTER_MOSI_IO
#define BNO08X_SPI_MISO_IO SPI_MASTER_MISO_IO
#define BNO08X_SPI_SCLK_IO SPI_MASTER_SCLK_IO
#define BNO08X_SPI_CS_IO 4
#define BNO08X_SPI_INT_IO 15
#define BNO08X_SPI_RST_IO 16
#define BNO08X_SPI_FREQ_HZ 1000000

#define PCA9685_I2C_ADDR 0x40
#define PCA9685_OSC_CLOCK_HZ 27000000UL

#define SERVO_FREQ_HZ 50
#define SERVO_MIN_US 500
#define SERVO_MAX_US 2500

/* Physical steering calibration measured on the vehicle. */
#define STEERING_PCA_CHANNEL 7
#define STEERING_CENTER_DEG 100
#define STEERING_LEFT_MECHANICAL_LIMIT_DEG 63
#define STEERING_RIGHT_MECHANICAL_LIMIT_DEG 139
#define STEERING_ENDPOINT_SAFETY_MARGIN_DEG 2
#define STEERING_LEFT_SAFE_DEG \
    (STEERING_LEFT_MECHANICAL_LIMIT_DEG + STEERING_ENDPOINT_SAFETY_MARGIN_DEG)
#define STEERING_RIGHT_SAFE_DEG \
    (STEERING_RIGHT_MECHANICAL_LIMIT_DEG - STEERING_ENDPOINT_SAFETY_MARGIN_DEG)
/* Never committed. Default: the mechanical limits minus the safety margin
 * (65/137 deg). Measure the running firmware's mapping before flashing
 * (steer_calib.py) and rebuild with -D overrides if it differs. */
#ifndef STEERING_LEFT_COMMAND_LIMIT_DEG
#define STEERING_LEFT_COMMAND_LIMIT_DEG (STEERING_LEFT_MECHANICAL_LIMIT_DEG + STEERING_ENDPOINT_SAFETY_MARGIN_DEG)
#endif
#ifndef STEERING_RIGHT_COMMAND_LIMIT_DEG
#define STEERING_RIGHT_COMMAND_LIMIT_DEG (STEERING_RIGHT_MECHANICAL_LIMIT_DEG - STEERING_ENDPOINT_SAFETY_MARGIN_DEG)
#endif
#define STEERING_UPDATE_INTERVAL_MS 15
#define STEERING_NORMAL_STEP_DEG 3
#define STEERING_RETURN_STEP_DEG 6
#define STEERING_ENDPOINT_STEP_DEG 2
#define STEERING_MAX_ENDPOINT_HOLD_MS 700
#define STEERING_ENDPOINT_RELIEF_DEG 4

/* Flipsky VESC UART configuration and conservative prototype limits. */
#define VESC_UART_PORT UART_NUM_2
#define VESC_UART_RX_IO 18
#define VESC_UART_TX_IO 17
#define VESC_UART_BAUD_RATE 115200
#define VESC_MAX_ABS_RPM 6300
#define VESC_SEND_INTERVAL_MS 20
#define VESC_TELEMETRY_INTERVAL_MS 200
#define VESC_TELEMETRY_TIMEOUT_MS 30
#define VESC_TELEMETRY_STALE_MS 1000
#define VESC_DIRECTION_CHANGE_NEUTRAL_MS 150
#define VESC_COMMAND_TIMEOUT_MS 500
/* Never committed; resend every cycle (= VESC_SEND_INTERVAL_MS), as the
 * pre-handoff firmware did, so the VESC always sees fresh commands. */
#define VESC_COMMAND_KEEPALIVE_MS VESC_SEND_INTERVAL_MS
